export const ADD_DISTRICT = 'ADD_DISTRICT'
export const REMOVE_DISTRICT = 'REMOVE_DISTRICT'
export const TOGGLE_MORE = 'TOGGLE_MORE'
export const ADD_CITY = 'ADD_CITY'
export const REMOVE_CITY = 'REMOVE_CITY'
